version: '3'

services:
  poe-to-gpt:
    image: ghcr.io/formzs/poe-to-gpt:latest
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "3770:3770"
    env_file:
      - .env
    volumes:
      - ./app.py:/app/app.py
    restart: unless-stopped